### ISSUE TITLE
The controller is not working at all...

### ISSUE THREAD

**Issue by wonchul-kim** [1989Ryan/Fuzzy-Control-Project#2]
Hi,

I executed your code (pid_result.py, fuzzy_result.py).
However, the controller is not working at all...
the pendulum does not stand straight as the demo.gif shows...

Do I have to do something more in your code??

**Comment by 1989Ryan** [comment]
Maybe you should tune the parameters of controller. Sorry there are no original parameters that I can provide. However, there should be no problems in the framework. You should not fully rely on my demo script.
