### ISSUE TITLE
PID controller cannot solve Pendulum-v0 on some initial states

### ISSUE THREAD

**Issue by keiohta** [1989Ryan/Fuzzy-Control-Project#3]
Hi @1989Ryan , thanks for providing the useful repository!

I want to ask why your PID controller cannot sometimes solve `Pendulum-v0` task.

- Is that limitation of PID controller?
- Can it be improved by tuning the PID gains?

I'm not familiar with classic control, so sorry if I have misunderstood something.

**Comment by 1989Ryan** [comment]
Hi @keiohta ,

Thank you for your interests in my project. However, this project was my course homework years ago and I cannot remember the details. If you want to implement the PID controller, the framework should be fine but you need to tune the P I D parameter to get best performance. You can also tune the sampling time in the framework as well. The initial parameter setup is missing and sorry that I may not be able to share with you. 

Best wishes,
Zirui

**Comment by keiohta** [comment]
Hi @1989Ryan , thank you for your kind reply.

Sure, I understand the situation and I'll try tuning the PID parameter by myself.

Best regards,
Kei
